# Generating completion file for Fish
# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_youtui_global_optspecs
    string join \n d/debug s/show-source i/input-json= g/generate-completions= a/auth-type= h/help V/version
end

function __fish_youtui_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_youtui_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_youtui_using_subcommand
    set -l cmd (__fish_youtui_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c youtui -n __fish_youtui_needs_command -s i -l input-json -d 'Process the passed Json file(s) as if received from YouTube Music. This parameter can be passed multiple times, processing multiple files if the endpoint supports continuations. If multiple files are passed but the endpoint doesn\'t support continuations, only the first one is processed' -r -F
complete -c youtui -n __fish_youtui_needs_command -s g -l generate-completions -d 'Generate shell completions for the specified shell' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c youtui -n __fish_youtui_needs_command -s a -l auth-type -d 'Force the use of an auth type' -r -f -a "oauth\t''
browser\t''
unauthenticated\t''"
complete -c youtui -n __fish_youtui_needs_command -s d -l debug -d 'Display and log additional debug information'
complete -c youtui -n __fish_youtui_needs_command -s s -l show-source -d 'Print the source output Json from YouTube Music\'s API instead of the processed value'
complete -c youtui -n __fish_youtui_needs_command -s h -l help -d 'Print help'
complete -c youtui -n __fish_youtui_needs_command -s V -l version -d 'Print version'
complete -c youtui -n __fish_youtui_needs_command -f -a get-search-suggestions
complete -c youtui -n __fish_youtui_needs_command -f -a get-artist
complete -c youtui -n __fish_youtui_needs_command -f -a get-artist-albums
complete -c youtui -n __fish_youtui_needs_command -f -a get-album
complete -c youtui -n __fish_youtui_needs_command -f -a get-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-playlists
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-artists
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-songs
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-albums
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-artist-subscriptions
complete -c youtui -n __fish_youtui_needs_command -f -a search
complete -c youtui -n __fish_youtui_needs_command -f -a search-artists
complete -c youtui -n __fish_youtui_needs_command -f -a search-albums
complete -c youtui -n __fish_youtui_needs_command -f -a search-songs
complete -c youtui -n __fish_youtui_needs_command -f -a search-playlists
complete -c youtui -n __fish_youtui_needs_command -f -a search-community-playlists
complete -c youtui -n __fish_youtui_needs_command -f -a search-featured-playlists
complete -c youtui -n __fish_youtui_needs_command -f -a search-videos
complete -c youtui -n __fish_youtui_needs_command -f -a search-episodes
complete -c youtui -n __fish_youtui_needs_command -f -a search-profiles
complete -c youtui -n __fish_youtui_needs_command -f -a search-podcasts
complete -c youtui -n __fish_youtui_needs_command -f -a create-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a delete-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a remove-playlist-items
complete -c youtui -n __fish_youtui_needs_command -f -a add-videos-to-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a add-playlist-to-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a edit-playlist-title
complete -c youtui -n __fish_youtui_needs_command -f -a get-history
complete -c youtui -n __fish_youtui_needs_command -f -a remove-history-items
complete -c youtui -n __fish_youtui_needs_command -f -a rate-song
complete -c youtui -n __fish_youtui_needs_command -f -a rate-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a edit-song-library-status
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-upload-songs
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-upload-artists
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-upload-albums
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-upload-artist
complete -c youtui -n __fish_youtui_needs_command -f -a get-library-upload-album
complete -c youtui -n __fish_youtui_needs_command -f -a delete-upload-entity
complete -c youtui -n __fish_youtui_needs_command -f -a get-taste-profile
complete -c youtui -n __fish_youtui_needs_command -f -a set-taste-profile
complete -c youtui -n __fish_youtui_needs_command -f -a get-mood-categories
complete -c youtui -n __fish_youtui_needs_command -f -a get-mood-playlists
complete -c youtui -n __fish_youtui_needs_command -f -a add-history-item
complete -c youtui -n __fish_youtui_needs_command -f -a get-song-tracking-url
complete -c youtui -n __fish_youtui_needs_command -f -a get-lyrics
complete -c youtui -n __fish_youtui_needs_command -f -a get-watch-playlist
complete -c youtui -n __fish_youtui_needs_command -f -a get-channel
complete -c youtui -n __fish_youtui_needs_command -f -a get-channel-episodes
complete -c youtui -n __fish_youtui_needs_command -f -a get-podcast
complete -c youtui -n __fish_youtui_needs_command -f -a get-episode
complete -c youtui -n __fish_youtui_needs_command -f -a get-new-episodes
complete -c youtui -n __fish_youtui_needs_command -f -a setup-oauth -d 'Generate an OAuth token'
complete -c youtui -n __fish_youtui_needs_command -f -a help -d 'Print this message or the help of the given subcommand(s)'
complete -c youtui -n "__fish_youtui_using_subcommand get-search-suggestions" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-artist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-artist-albums" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-album" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-playlists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-artists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-songs" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-albums" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-artist-subscriptions" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-artists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-albums" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-songs" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-playlists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-community-playlists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-featured-playlists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-videos" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-episodes" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-profiles" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand search-podcasts" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand create-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand delete-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand remove-playlist-items" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand add-videos-to-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand add-playlist-to-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand edit-playlist-title" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-history" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand remove-history-items" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand rate-song" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand rate-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand edit-song-library-status" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-upload-songs" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-upload-artists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-upload-albums" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-upload-artist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-library-upload-album" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand delete-upload-entity" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-taste-profile" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand set-taste-profile" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-mood-categories" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-mood-playlists" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand add-history-item" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-song-tracking-url" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-lyrics" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-watch-playlist" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-channel" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-channel-episodes" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-podcast" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-episode" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand get-new-episodes" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand setup-oauth" -s f -l file-name -d 'Optional: Write to a specific file instead of the config directory' -r -F
complete -c youtui -n "__fish_youtui_using_subcommand setup-oauth" -s s -l stdout -d 'Optional: Print to stdout instead of the config directory'
complete -c youtui -n "__fish_youtui_using_subcommand setup-oauth" -s h -l help -d 'Print help'
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-search-suggestions
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-artist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-artist-albums
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-album
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-playlists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-artists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-songs
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-albums
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-artist-subscriptions
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-artists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-albums
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-songs
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-playlists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-community-playlists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-featured-playlists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-videos
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-episodes
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-profiles
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a search-podcasts
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a create-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a delete-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a remove-playlist-items
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a add-videos-to-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a add-playlist-to-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a edit-playlist-title
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-history
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a remove-history-items
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a rate-song
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a rate-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a edit-song-library-status
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-upload-songs
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-upload-artists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-upload-albums
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-upload-artist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-library-upload-album
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a delete-upload-entity
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-taste-profile
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a set-taste-profile
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-mood-categories
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-mood-playlists
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a add-history-item
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-song-tracking-url
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-lyrics
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-watch-playlist
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-channel
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-channel-episodes
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-podcast
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-episode
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a get-new-episodes
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a setup-oauth -d 'Generate an OAuth token'
complete -c youtui -n "__fish_youtui_using_subcommand help; and not __fish_seen_subcommand_from get-search-suggestions get-artist get-artist-albums get-album get-playlist get-library-playlists get-library-artists get-library-songs get-library-albums get-library-artist-subscriptions search search-artists search-albums search-songs search-playlists search-community-playlists search-featured-playlists search-videos search-episodes search-profiles search-podcasts create-playlist delete-playlist remove-playlist-items add-videos-to-playlist add-playlist-to-playlist edit-playlist-title get-history remove-history-items rate-song rate-playlist edit-song-library-status get-library-upload-songs get-library-upload-artists get-library-upload-albums get-library-upload-artist get-library-upload-album delete-upload-entity get-taste-profile set-taste-profile get-mood-categories get-mood-playlists add-history-item get-song-tracking-url get-lyrics get-watch-playlist get-channel get-channel-episodes get-podcast get-episode get-new-episodes setup-oauth help" -f -a help -d 'Print this message or the help of the given subcommand(s)'
