#!/usr/bin/env bash
# set true color
# set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g default-terminal "tmux-256color"
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -as terminal-overrides ',xterm*:RGB'
set -g set-titles on
set -g set-titles-string "#T"

# change the default prefix key
unbind C-b
set -g prefix C-f
bind C-f send-prefix

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift Alt vim keys to navigate the windows
bind -n M-H previous-window
bind -n M-L next-window

# plugins to my needs
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'spywhere/tmux-named-snapshot' # testar depois
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin '27medkamal/tmux-session-wizard'

# Sessionist
    #
    # prefix + g - prompts for session name and switches to it. Performs 'kind-of' name completion.
    # Faster than the built-in prefix + s prompt for long session lists.
    # prefix + C (shift + c) - prompt for creating a new session by name.
    # prefix + X (shift + x) - kill current session without detaching tmux.
    # prefix + S (shift + s) - switches to the last session.
    # The same as built-in prefix + L that everyone seems to override with some other binding.
    # prefix + @ - promote current pane into a new session.
    # Analogous to how prefix + ! breaks current pane to a new window.
    # prefix + ctrl-@ - promote current window into a new session.
    # prefix + t<secondary-key> - join currently marked pane (prefix + m) to current session/window, and switch to it
    #     secondary-keys
    #         h, -, ": join horizontally
    #         v, |, %: join vertically
    #         f, @: join full screen

# Named Session Restore
    # Prefix + Ctrl-m: Save 'manual' snapshot
    # Prefix + M: Prompt for a name and save the snapshot under that name
    # Prefix + Ctrl-n: Restore 'manual' snapshot
    # Prefix + N: Prompt for a name and restore the snapshot by that name
    #

run '~/.tmux/plugins/tpm/tpm'

# Some settings for tmux-continuum
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'ghostty'
set -g @continuum-restore 'on'

set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"

# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# split the panel in cwd
bind '|' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"


# Add support to image preview in yazi

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
