# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0E0F1D)
$foreground = rgb(B7B8C8)
$color0 = rgb(40242B)
$color1 = rgb(333872)
$color2 = rgb(333872)
$color3 = rgb(333872)
$color4 = rgb(333872)
$color5 = rgb(7A3064)
$color6 = rgb(963363)
$color7 = rgb(8F91A7)
$color8 = rgb(646575)
$color9 = rgb(393F84)
$color10 = rgb(393F85)
$color11 = rgb(393F85)
$color12 = rgb(393F85)
$color13 = rgb(8F3574)
$color14 = rgb(B53874)
$color15 = rgb(8F91A7)
