# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(191B20)
$foreground = rgb(EAEDE6)
$color0 = rgb(43474C)
$color1 = rgb(207496)
$color2 = rgb(306B96)
$color3 = rgb(2E7AA1)
$color4 = rgb(346F90)
$color5 = rgb(7A8629)
$color6 = rgb(6C9A3E)
$color7 = rgb(D8DDD3)
$color8 = rgb(979B93)
$color9 = rgb(1E87B0)
$color10 = rgb(2E75A8)
$color11 = rgb(2989BA)
$color12 = rgb(3780A8)
$color13 = rgb(9CAA31)
$color14 = rgb(95CD52)
$color15 = rgb(D8DDD3)
