# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1B0B0D)
$foreground = rgb(FBF8EE)
$color0 = rgb(0F0000)
$color1 = rgb(B6AF9A)
$color2 = rgb(9A7C68)
$color3 = rgb(718684)
$color4 = rgb(A16E68)
$color5 = rgb(59656A)
$color6 = rgb(704F52)
$color7 = rgb(F0ECDE)
$color8 = rgb(A8A59B)
$color9 = rgb(F3EACE)
$color10 = rgb(CDA58B)
$color11 = rgb(5F8380)
$color12 = rgb(BA6962)
$color13 = rgb(637379)
$color14 = rgb(82565B)
$color15 = rgb(F0ECDE)
