# preferred_background: 191B20
# based on: 'https://github.com/chriskempson/base16-default-schemes'

fish_color_normal 1E87B0
fish_color_autosuggestion 2E7AA1
fish_color_cancel 7A8629
fish_color_command 1E87B0
fish_color_comment D8DDD3
fish_color_cwd 306B96
fish_color_cwd_root 346F90
fish_color_end 95CD52
fish_color_error 2E75A8
fish_color_escape 3780A8
fish_color_history_current D8DDD3
fish_color_host 207496
fish_color_host_remote 6C9A3E
fish_color_keyword 207496
fish_color_operator 1E87B0
fish_color_option 7A8629
fish_color_param 306B96
fish_color_quote D8DDD3
fish_color_redirection 7A8629
fish_color_search_match white --background=191B20 --bold
fish_color_selection 9CAA31 --background=D8DDD3 --bold
fish_color_status 207496
fish_color_user 9FB7C3
fish_color_valid_path 9CAA31 --underline
fish_pager_color_completion 979B93
fish_pager_color_description B3A06D 6C9A3E
fish_pager_color_prefix normal --bold --underline
fish_pager_color_progress brwhite --background=cyan --bold
fish_pager_color_selected_background --background=D8DDD3
fish_pager_color_background EAEDE6
