# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B7B8C8
background         #0E0F1D
cursor             #926F90

active_tab_foreground     #0E0F1D
active_tab_background     #B7B8C8
inactive_tab_foreground   #B7B8C8
inactive_tab_background   #0E0F1D

active_border_color   #B7B8C8
inactive_border_color #0E0F1D
bell_border_color     #333872

color0      #40242B
color1		#333872
color2		#333872
color3		#333872
color4		#333872
color5		#7A3064
color6		#963363
color7		#8F91A7
color8		#646575
color9		#393F84
color10		#393F85
color11		#393F85
color12		#393F85
color13		#8F3574
color14		#B53874
color15		#8F91A7
