# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8F2F4
background         #110C18
cursor             #F193BC

active_tab_foreground     #110C18
active_tab_background     #E8F2F4
inactive_tab_foreground   #E8F2F4
inactive_tab_background   #110C18

active_border_color   #E8F2F4
inactive_border_color #110C18
bell_border_color     #CD1D79

color0      #3B3745
color1		#CD1D79
color2		#CA2868
color3		#2F5FA8
color4		#2588AD
color5		#BF373F
color6		#4092A9
color7		#D6E4E7
color8		#969FA2
color9		#FF0588
color10		#FA1871
color11		#306FCD
color12		#31B5E6
color13		#FF4A54
color14		#56C1E1
color15		#D6E4E7
