# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EAEDE6
background         #191B20
cursor             #9FB7C3

active_tab_foreground     #191B20
active_tab_background     #EAEDE6
inactive_tab_foreground   #EAEDE6
inactive_tab_background   #191B20

active_border_color   #EAEDE6
inactive_border_color #191B20
bell_border_color     #207496

color0      #43474C
color1		#207496
color2		#306B96
color3		#2E7AA1
color4		#346F90
color5		#7A8629
color6		#6C9A3E
color7		#D8DDD3
color8		#979B93
color9		#1E87B0
color10		#2E75A8
color11		#2989BA
color12		#3780A8
color13		#9CAA31
color14		#95CD52
color15		#D8DDD3
